### ISSUE TITLE
pip installed foodframe missing dependencies

### ISSUE THREAD

**Issue by dacb** [AnnieKLamar/foodframe#1]
I was able to pip install foodframe without an issue into a fresh conda environment.  When I try to `import foodframe` I see a `ModuleNotFound` error that is probably related to a missing dependency in the `foodframe` egg.

```
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import foodframe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dacb/miniconda3/lib/python3.11/site-packages/foodframe/__init__.py", line 2, in <module>
    from hei import *
ModuleNotFoundError: No module named 'hei'
>>>
```

**Comment by AnnieKLamar** [comment]
This should be fixed in the GitHub release now--I'm fixing a few more things before pushing a new version to PyPi.

@Tushar: The problem with the import was in the `__init__.py` file. When you import Python files that are the local to the project, you have the include the full path so the system knows where to look. The easiest way to fix this is by adding a "." before the package name, e.g. from `from .hei import *`.
